replicaCount: 1

image:
  repository: flowiseai/flowise
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.3.9"

service:
  type: ClusterIP
  port: 3000

env:
  PORT: "3000"
  DATABASE_PATH: "/root/.flowise"
  APIKEY_PATH: "/root/.flowise"
  SECRETKEY_PATH: "/root/.flowise"
  LOG_PATH: "/root/.flowise/logs"
  # Uncomment and set the rest of the environment variables as needed
  # FLOWISE_USERNAME: "user"
  # FLOWISE_PASSWORD: "1234"
  # FLOWISE_SECRETKEY_OVERWRITE: "myencryptionkey"
  # DEBUG: "true"
  # LOG_LEVEL: "debug"
  # Add more environment variables as needed

# Define your volume mounts here if necessary
volumes: []
volumeMounts: []

# Add any other necessary Kubernetes resource configurations here
